name: Manual Trigger Workflow

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Secret (masked)
        run: echo "The secret is ${{ secrets.MY_SECRET }}"
