on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your name'
        required: true
        default: 'Aftab'

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ github.event.inputs.username }}!"
