name: Manual Workflow demo

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your name'
        required: true
        default: 'Aftab'
      message:
        description: 'Custom message'
        required: false
        default: 'This workflow was triggered manually'

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "Hello ${{ github.event.inputs.username }}! -> ${{ github.event.inputs.message }}"
